### ISSUE TITLE
Bing not recording conversion goals

### ISSUE THREAD

**Issue by messagerichard** [managed-components/bing#3]
Hi

I have set up Bing in Zaraz using the managed component. My domain is www.tradetested.co.nz.

UET events are coming through to Bing:

<img width="1490" alt="Screen Shot 2023-04-21 at 9 03 26 PM" src="https://user-images.githubusercontent.com/4902048/233594734-1fac3a9f-a18c-4035-bdf7-f8485c2cf559.png">

But I haven't been able to get a conversion goal for purchase/checkout success to record any conversions. I have tried setting up the conversion goal in Bing a few different ways (and waited each time).

**Comment by tomfuertes** [comment]
+1 also had this issue / same setup and UET events showing as counting / same "0" in conversions

**Comment by bjesus** [comment]
We will welcome a PR here. If you can provide an example for a Bing request that is created with the original Bing pixel and is recording conversions, please send it so we can perhaps see what's missing on the component side.

**Comment by tgowing** [comment]
In our investigation we concluded that the bing component is not working because:

 - the event values and names are not encoded (for example: spaces are rendered as + instead of %20)
 - the msclkid value is not being sent correctly: currently it is sent as 0 or 1. Instead it should be the value of the msclkid followed by a dash and suffix (0 or 1)
 
Perhaps the main problem is not sending the msclkid correctly. This is computed here:

https://github.com/managed-components/bing/blob/dd1179d1399b0723fb26d84f171b1b8ebedd4e8a/src/index.ts#L115-L136

On line 129 there is a check to get the msclkid from the payload, otherwise it will not add it at all. But there is no way to set the msclkid in the payload since there is no such field in the UI:

![Screenshot 2024-03-15 at 6 08 59 AM](https://github.com/managed-components/bing/assets/11142114/203bcf5f-7c65-414c-803c-2141e87f14d1)

Below you can see the difference between the working pixel from Microsfot (left side) and the current bing component url (right side).


![Screenshot 2024-03-14 at 7 48 09 PM](https://github.com/managed-components/bing/assets/11142114/c76802fe-bcc8-4bbf-a14d-db37faa30de2)

**Comment by bjesus** [comment]
hey @tgowing , line 129 isn't getting `msclkid` from the payload, it's getting it from using client.get, which is effectively getting it from a cookie (created with client.set on line 122, based on the `msclkid` query parameter).

Can you try to export your Zaraz config and check if the the Bing Managed Component has the `access_client_kv` permission?

**Comment by tgowing** [comment]
@bjesus, thanks very much for getting back to me, no it doesn't have them set the Bing component just has "client_network_requests" in the permissions array, where as I can see the other tools do have the "access_client_kv". How do I set this?

Actually, I have just reset up the Bing tool from scratch in the CF interface and I'm now seeing the "access_client_kv" in the json output and when I test the events they include the msclkid correctly. 

So thank you very much for your time and help!
